version: "1.0"
name: pipeline-20220602
displayName: build
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ""
stages:
  - name: stage-7edba1d9
    displayName: 依赖环境
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: "3.8.3"
        commands:
          - python3 -m pip install --upgrade pip
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install -r ./api/requirements.txt
        strategy:
          retry: "0"
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - npm install -g pnpm
          - pnpm add -g nrm
          - nrm use taobao
          - pnpm install
        strategy:
          retry: "0"
permissions:
  - role: admin
    members: []
