// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CalcButton: typeof import('./src/components/calc/button/index.vue')['default']
    CalcCheckbox: typeof import('./src/components/calc/checkbox/index.vue')['default']
    CalcDialog: typeof import('./src/components/calc/dialog/index.vue')['default']
    CalcIconselect: typeof import('./src/components/calc/iconselect/index.vue')['default']
    CalcMenuMenu: typeof import('./src/components/calc/menu/menu.vue')['default']
    CalcOption: typeof import('./src/components/calc/option/index.vue')['default']
    CalcSelect: typeof import('./src/components/calc/select/index.vue')['default']
    CalcTab: typeof import('./src/components/calc/tab/index.vue')['default']
    CalcTabs: typeof import('./src/components/calc/tabs/index.vue')['default']
    CalcTooltip: typeof import('./src/components/calc/tooltip/index.vue')['default']
    InternalCharinfo: typeof import('./src/components/internal/charinfo/index.vue')['default']
    InternalEquipEqChoose: typeof import('./src/components/internal/equip/eq-choose.vue')['default']
    InternalEquipEqIcon: typeof import('./src/components/internal/equip/eq-icon.vue')['default']
    InternalEquipEqIconTips: typeof import('./src/components/internal/equip/eq-icon-tips.vue')['default']
    InternalEquipEqInfo: typeof import('./src/components/internal/equip/eq-info.vue')['default']
    InternalSkillSkillIcon: typeof import('./src/components/internal/skill/skill-icon.vue')['default']
    InternalSkillSkillPanel: typeof import('./src/components/internal/skill/skill-panel.vue')['default']
    Show: typeof import('./src/components/show.vue')['default']
  }
}

export { }
