// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CalcAutocomplete: typeof import('./src/components/calc/autocomplete/index.vue')['default']
    CalcButton: typeof import('./src/components/calc/button/index.vue')['default']
    CalcCheckbox: typeof import('./src/components/calc/checkbox/index.vue')['default']
    CalcCollapse: typeof import('./src/components/calc/collapse/index.vue')['default']
    CalcDialog: typeof import('./src/components/calc/dialog/index.vue')['default']
    CalcIconselect: typeof import('./src/components/calc/iconselect/index.vue')['default']
    CalcItem: typeof import('./src/components/calc/item/index.vue')['default']
    CalcMenuMenu: typeof import('./src/components/calc/menu/menu.vue')['default']
    CalcOption: typeof import('./src/components/calc/option/index.vue')['default']
    CalcSelect: typeof import('./src/components/calc/select/index.vue')['default']
    CalcSelection: typeof import('./src/components/calc/selection/index.vue')['default']
    CalcTab: typeof import('./src/components/calc/tab/index.vue')['default']
    CalcTabs: typeof import('./src/components/calc/tabs/index.vue')['default']
    CalcTooltip: typeof import('./src/components/calc/tooltip/index.vue')['default']
    CalcTree: typeof import('./src/components/calc/tree/index.vue')['default']
    CalcTreeNode: typeof import('./src/components/calc/tree/node.vue')['default']
    InternalEquipEqIcon: typeof import('./src/components/internal/equip/eq-icon.vue')['default']
    InternalEquipEqIconTips: typeof import('./src/components/internal/equip/eq-icon-tips.vue')['default']
    InternalEquipEqInfo: typeof import('./src/components/internal/equip/eq-info.vue')['default']
    InternalEquipEquipList: typeof import('./src/components/internal/equip/equip-list.vue')['default']
    InternalProfile: typeof import('./src/components/internal/profile.vue')['default']
    InternalSkillSkillIcon: typeof import('./src/components/internal/skill/skill-icon.vue')['default']
    InternalSkillSkillPanel: typeof import('./src/components/internal/skill/skill-panel.vue')['default']
    Show: typeof import('./src/components/show.vue')['default']
  }
}

export { }
